export interface MakeOrder {
  id: number;
  farmGuid: string;
  customerGuid: string;
  orderNo: string;
  orderName: string;
  orderDate: any | null;
  deliveryDate: any | null;
  estimateStartDate: any | null;
  estimateEndDate: any | null;
  realStartDate: any | null;
  realEndDate: any | null;
  orderBreed: string;
  orderAmound: number | null;
  orderType: string;
  orderFarm: string;
  orderPrice: number | null;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  pigType: string;
  bomGuid: string;
  roomGuid: string;
  inAmound: number | null;
  currentAmound: number | null;
  cullingAmound: number | null;
  deathAmound: number | null;
  saleAmound: number | null;
  donateAmound: number | null;
  closeDate: any | null;
  closeReason: string;
  closeGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
}
