export interface Dashboard {
    id: number;
    farmGuid: string;
    dashBoardNo: number | null;
    dashBoardName: string;
    upperDashBoard: string;
    areaNo: number | null;
    areaName: string;
    upperArea: string;
    itemNo: number | null;
    itemName: string;
    backGroundColor: string;
    type: string;
    sortId: number | null;
    text01: string;
    text02: string;
    text03: string;
    text04: string;
    text05: string;
    text06: string;
    text07: string;
    text08: string;
    text09: string;
    text10: string;
    textColor01: string;
    textColor02: string;
    textColor03: string;
    textColor04: string;
    textColor05: string;
    textColor06: string;
    textColor07: string;
    textColor08: string;
    textColor09: string;
    textColor10: string;
    value01: string;
    value02: string;
    value03: string;
    value04: string;
    value05: string;
    value06: string;
    value07: string;
    value08: string;
    value09: string;
    value10: string;
    valueColor01: string;
    valueColor02: string;
    valueColor03: string;
    valueColor04: string;
    valueColor05: string;
    valueColor06: string;
    valueColor07: string;
    valueColor08: string;
    valueColor09: string;
    valueColor10: string;
    createDate: string | null;
    createBy: number | null;
    status: number | null;
    guid: string;
    chartTitle: string;
    langID: string;
}
