export interface Employee {
  id: number;
  name: string;
  no: string;
  sex: any;
  nickName: string;
  tel: string;
  mobile: string;
  address: string;
  addressDomicile: string;
  idCard: string;
  email: string;
  comment: string;
  unit: string;
  dept: string;
  level: string;
  contactName: string;
  contactTel: string;
  birthDay: any;
  startDate: string | null;
  endDate: string | null;
  status: number | null;
  createBy: number;
  updateBy: number | null;
  deleteBy: number | null;
  createDate: string| null;
  updateDate: string | null;
  deleteDate: string | null;
  sexName: any;
}
