export interface VectorControl {
  id: number;
  vectorControlType: string;
  vectorControlNo: string;
  vectorControlName: string;
  vectorControlElement: string;
  vectorControlEffect: string;
  vectorControlSideEffect: string;
  vectorControlBreed: string;
  vectorControlRange: string;
  vectorControlCare: string;
  comment: string;
  cancelFlag: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  status: number | null;
  guid: string;
  farmGuid: string;
  deleteDate: string | null;
  deleteBy: number | null;
  vendorGuid: string;
  location: string;
  spec: string;
  amount: number | null;
  price: number | null;
  cost: number | null;
  expireDate: any| null;
}
