export interface XAccount {
  accountId: number;
  clinicId: number | null;
  uid: string;
  upwd: string;
  accountNo: string;
  accountName: string;
  accountSex: string;
  accountBirthday: string | null;
  accountNickname: string;
  accountTel: string;
  accountMobile: string;
  accountAddress: string;
  accountIdcard: string;
  accountEmail: string;
  startDate: string | null;
  endDate: string | null;
  lastlogin: string | null;
  lastuse: string | null;
  comment: string;
  status: string;
  token: string;
  cancelFlag: string;
  createBy: number | null;
  createDate: string | null;
  updateBy: number | null;
  updateDate: string | null;
  pAdmin: string;
  pAccount: string;
  pPatient: string;
  pRequisitionConfirm: string;
  pPhotoComment: string;
  lastLoginDate: string | null;
  pClinic: string;
  pCodeType: string;
  pEnquiry: string;
  pEnquiryResult: string;
  guid: string;
  roleId: number | null;
  typeId: number | null;
  farmGuid: string;
  accountRole: string;
  accountType: string;
  accountGroup: string;
  accountOrganization: number | null;
  accountSite: number | null;
  errorLogin: number | null;
  photoPath: string;
  employeeGuid: string;
  accountDomicileAddress: string;
  file: any;
}
export interface Profile {
  nickName: string;
  accountGuid: string;
  accountId:number;
  tel: string;
  mobile: string;
  address: string;
  addressDomicile: string;
  email: string;
  comment: string;
  contactName: string;
  contactTel: string;
  photoPath: string;
  pageSizeSetting: string;
  pageSizeSettingValue: string;
  pageSizeSettingList: string;
}
