// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PigFarm.Models
{
    public partial class BioS2pen
    {
        public decimal Id { get; set; }
        public string BioSMasterGuid { get; set; }
        public string PenGuid { get; set; }
    }
}