// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PigFarm.Models
{
    public partial class BomFeeding
    {
        public int Id { get; set; }
        public string BomGuid { get; set; }
        public string FeedType { get; set; }
        public string FeedName { get; set; }
        public string FeedGuid { get; set; }
        public string UseType { get; set; }
        public string UseUnit { get; set; }
        public string Frequency { get; set; }
        public string EstAmount { get; set; }
        public string RecordAmount { get; set; }
        public string RecordResult { get; set; }
        public string Comment { get; set; }
        public string CancelFlag { get; set; }
        public DateTime? CreateDate { get; set; }
        public decimal? CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public decimal? UpdateBy { get; set; }
        public decimal? Status { get; set; }
        public string Guid { get; set; }
        public int? ApplyDays { get; set; }
    }
}