// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PigFarm.Models
{
    public partial class BomWeighing
    {
        public int Id { get; set; }
        public string BomGuid { get; set; }
        public string WeighingType { get; set; }
        public string WeighingName { get; set; }
        public string UseType { get; set; }
        public string UseUnit { get; set; }
        public string Frequency { get; set; }
        public string ApplyDays { get; set; }
        public string Comment { get; set; }
        public string CancelFlag { get; set; }
        public DateTime? CreateDate { get; set; }
        public decimal? CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public decimal? UpdateBy { get; set; }
        public decimal? Status { get; set; }
        public string Guid { get; set; }
        public decimal? StandardWeight { get; set; }
    }
}