export class StatusConstants {
  Default = 1;
  Agree = 2;
  Execute = 3;
  Close = 3;
  Reject = 5;
  Delete = -1;
}
export interface Record2Pig {
  id: number;
  type: string;
  recordGuid: string;
  pigGuid: string;
  recordValue: string;
  recordWeight: number | null;
  recordAmount: number | null;
  recordDisease: string;
  recordDiseaseName: string;
  recordNext: string;
}

export interface UpdateWeightParams {
  type: string;
  recordGuid: string;
  recordValue: string;
}
export interface RecordBuried {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  buriedMethod: number | null;
  buriedReason: string;
  buriedWeight: number | null;
  typeName: string;
  statusName: string;
  pigs: string[];
  record2Pigs: any[];
  roomGuid: string;
  penGuid: string;
  pens: string[];
  upperGuid: string;
  upperRecord: string;
}
export interface RecordChemical {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  chemicalMethod: number | null;
  chemicalReason: string;
  chemicalWeight: number | null;
  typeName: string;
  statusName: string;
  pigs: string[];
  record2Pigs: any[];
  roomGuid: string;
  penGuid: string;
  pens: string[];
  upperGuid: string;
  upperRecord: string;
}
export interface RecordKill {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  killMethod: number | null;
  killReason: string;
  killWeight: number | null;
  typeName: string;
  statusName: string;
  pigs: string[];
  roomGuid: string;
  penGuid: string;
  pens: string[];
  upperGuid: string;
  upperRecord: string;
}
export interface RecordPigIn {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  inOutNo: string;
  inOutName: string;
  fromFarm: string;
  toFarm: string;
  pigInfor: string;
  inOutReason: string;
  inOutSource: string;
  inOutDept: string;
  inOutAmount: number | null;
  inOutWeight: number | null;
  typeName: string;
  statusName: string;
  record2Pigs: any[];
  pigs: string[];
  roomGuid: string;
  penGuid: string;
  pens: string[];
  upperGuid: string;
  upperRecord: string;
  veterinaryDate: any | null;
  veterinaryReason: string;
  veterinaryGuid: string;
  sourceOrderNo: string;
  sourceAmount: number | null;
  sourceTotalWeight: number | null;
  realAmount: number | null;
  realTotalWeight: number | null;
}

export interface RecordPigOut {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  inOutNo: string;
  inOutName: string;
  fromFarm: string;
  toFarm: string;
  pigInfor: string;
  inOutReason: string;
  inOutSource: string;
  inOutDept: string;
  inOutAmount: number | null;
  inOutWeight: number | null;
  typeName: string;
  statusName: string;
  record2Pigs: any[];
  pigs: string[];
  roomGuid: string;
  penGuid: string;
  pens: string[];
  upperGuid: string;
  upperRecord: string;
  veterinaryDate: any | null;
  veterinaryReason: string;
  veterinaryGuid: string;
}
export interface RecordStolen {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  stolenNo: string;
  stolenName: string;
  stolenAmount: number | null;
  typeName: string;
  statusName: string;
  pigs: string[];
  roomGuid: string;
  penGuid: string;
  pens: string[];
  upperGuid: string;
  upperRecord: string;
  inventoryDate: any | null;
  inventoryReason: string;
  inventoryGuid: string;
}
export interface RecordSilo {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  upperRecord: string;
  upperGuid: string;
  executeAmount: number | null;
  executeFeedGuid: string;
  estAmount: number | null;
  remainingAmount: number | null;
  realAmount: number | null;
  feedCost: number | null;
  recordNo: string;
  pigs: string[];
  roomGuid: string;
  penGuid: string;
  pens: string[];
}
export interface RecordCullingSale {
  id: number;
  farmGuid: string;
  makeOrderGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  upperRecord: string;
  upperGuid: string;
  salesOrderNo: string;
  salesOrderName: string;
  salesOrderComment: string;
  customerGuid: string;
  accountGuid: string;
  uploadDocument: string;
  pigs: string[];
  record2Pigs: any[];
  statusName: string;
  pens: string[];
  roomGuid: string;
  penGuid: string;
  applyName: string;
  agreeName: string;
  rejectName: string;
  salesOrderAmount: number | null;
  executeName: string;
  roomName: string;
  accountName: string;
  customerName: string;
  salesOrderWeight: number |null;
}
export interface RecordCulling {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  cullingMethod: number | null;
  cullingWeight: number | null;
  cullingReason: string;
  pigs: string[];
  record2Pigs: any[];
  pens: string[];
  upperGuid: string;
  upperRecord: string;
}

export interface RecordDeath {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  deathMethod: number | null;
  deathReason: string;
  deathWeight: number | null;
  pigs: string[];
  record2Pigs: any[];
  pens: string[];
  upperGuid: string;
  upperRecord: string;
}

export interface RecordDiagnosis {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  diagnosis: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  upperRecord: string;
  upperGuid: string;
  inventoryDate: any | null;
  inventoryReason: string;
  inventoryGuid: string;
  veterinaryDate: any | null;
  veterinaryReason: string;
  veterinaryGuid: string;
  diagnosisAmount: number | null;
  diagnosisDescribe: string;
  diagnosisNo: string;
  diagnosisDate: any | null;
  diagnosisWithdrawalDate: any | null;
  diagnosisWithdrawalDays: number | null;
  diagnosisDoctor: string;
  diagnosisPhysician: string;
  diagnosisSymptom: string;
  diagnosisCheck: string;
  diagnosisTreatment: string;
  diagnosisMedicine: string;
  diagnosisDose: number | null;
  diagnosisWay: string;
  diagnosisFirstDosDay: any | null;
  diagnosisTimes: any | null;
  roomGuid: string;
  penGuid: string;
  pigs: string[];
  record2Pigs: any[];
  pens: string[];

}


export interface RecordDisinfection {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  disinfectionGuid: string;
  useType: string;
  useUnit: string;
  capacity: string;
  frequency: string;
  applyDays: string;
  pens: string[];
  upperGuid: string;
  upperRecord: string;
  inventoryDate: any | null;
  inventoryReason: string;
  inventoryGuid: string;
  areaGuid: string;
  barnGuid: string;
}

export interface RecordDonate {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  donateNo: string;
  donateName: string;
  donateComment: string;
  uploadDocument: string;
  pigs: string[];
  record2Pigs: any[];
  roomGuid: string;
  penGuid: string;
  pens: string[];
  upperGuid: string;
  upperRecord: string;
  inventoryDate: any | null;
  inventoryReason: string;
  inventoryGuid: string;
  donateAmound: number | null;
}

export interface RecordEarTag {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  earNo: string;
  earTagNo: string;
  rfid: string;
  record2Pigs: any[];
  pigs: string[];
  pens: string[];
  upperGuid: string;
  upperRecord: string;
  inventoryDate: any | null;
  inventoryReason: string;
  inventoryGuid: string;
}
export interface RecordFeeding {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  feedGuid: string;
  useType: string;
  useUnit: string;
  frequency: string;
  estAmount: string;
  recordAmount: string;
  recordResult: string;
  pigs: string[];
  pens: string[];
  upperGuid: string;
  upperRecord: string;
  makeOrderAmound: number | null;
  makeOrderDayAge : number | null;
  intakeStandard : number | null;
  intakeReal : number | null;
  intakeAverage : number | null;
  record2Pigs: any[];


}
export interface RecordGeneral {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  pigs: string[];
  upperGuid: string;
  upperRecord: string;
}

export interface RecordImmunization {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  diseaseGuid: string;
  medicineGuid: string;
  useType: string;
  useUnit: string;
  capacity: string;
  frequency: string;
  needle: string;
  applyDays: string;
  pens: string[];
  upperGuid: string;
  upperRecord: string;
  pigs: string[];
  inventoryDate: any | null;
  inventoryReason: string;
  inventoryGuid: string;

  veterinaryDate: any | null;
  veterinaryReason: string;
  veterinaryGuid: string;
}

export interface RecordInOut {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  inOutNo: string;
  inOutName: string;
  fromFarm: string;
  toFarm: string;
  typeName: string;
  pigs: string[];
  pigInfor: string;
  inOutReason: string;
  inOutSource: string;
  inOutDept: string;
  inOutAmount: number | null;
  inOutWeight: number | null;
  upperGuid: string;
  upperRecord: string;

}

export interface RecordInventoryCheck {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  inventoryCheckNo: string;
  inventoryCheckName: string;
  inventoryCheckAmount: number | null;
  pigs: string[];
  pens: string[];
  upperGuid: string;
  upperRecord: string;
  roomGuid: string;

  financeDate: any | null;
  financeReason: string;
  financeGuid: string;
}

export interface RecordMove {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  beforePenGuid: string;
  afterPenGuid: string;
  pigStatus: string;
  moveType: string;
  moveInOut: string;
  applyDays: string;
  beforePenName: string;
  afterPenName: string;
  moveInOutName: string;
  applyDaysName: string;
  pigStatusName: string;
  moveTypeName: string;
  typeName: string;
  delayReason: string;
  delayDays: number | null;
  pigs: string[];
  pens: string[];
  upperGuid: string;
  upperRecord: string;
}

export interface RecordPatrol {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  patrolNo: string;
  patrolName: string;
  roomGuid: string;
  penGuid: string;
  pigs: string[];
  pens: string[];
  upperGuid: string;
  upperRecord: string;
  inventoryDate: any | null;
  inventoryReason: string;
  inventoryGuid: string;
}
export interface RecordRepair {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  pigGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  repair: string;
  roomGuid: string;
  penGuid: string;
  pigs: string[];
  pens: string[];
  upperGuid: string;
  upperRecord: string;
}

export interface RecordSale {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  salesOrderDate: string | null;
  salesOrderTime: string;
  salesOrderNo: string;
  salesOrderName: string;
  salesOrderComment: string;
  customerGuid: string;
  accountGuid: string;
  uploadDocument: string;
  pigs: string[];
  record2Pigs: any[];
  pens: string[];
  upperGuid: string;
  upperRecord: string;
}

export interface RecordTower {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  roomGuid: string;
  penGuid: string;
  pigs: string[];
  upperGuid: string;
  upperRecord: string;
}

export interface RecordVectorControl {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  vectorControlGuid: string;
  useType: string;
  useUnit: string;
  capacity: string;
  frequency: string;
  applyDays: string;
  pens: string[];
  upperGuid: string;
  upperRecord: string;
  pigs: string[];
  inventoryDate: any | null;
  inventoryReason: string;
  inventoryGuid: string;
  areaGuid: string;
  barnGuid: string;
}

export interface RecordWeighing {
  id: number;
  farmGuid: string;
  type: string;
  makeOrderGuid: string;
  roomGuid: string;
  penGuid: string;
  comment: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  deleteDate: string | null;
  deleteBy: number | null;
  status: number | null;
  guid: string;
  estDate: any | null;
  applyDate: any | null;
  applyReason: string;
  applyGuid: string;
  agreeDate: any | null;
  agreeReason: string;
  agreeGuid: string;
  rejectDate: any | null;
  rejectReason: string;
  rejectGuid: string;
  executeDate: any | null;
  executeReason: string;
  executeGuid: string;
  netWeight: number | null;
  weight: number | null;
  useType: string;
  recordResult: string;
  pigs: string[];
  record2Pigs: any[];
  pens: string[];
  upperGuid: string;
  upperRecord: string;
}
