// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PigFarm.DTO
{
    public partial class Record2PigDto
    {
        public decimal Id { get; set; }
        public string Type { get; set; }
        public string RecordGuid { get; set; }
        public string PigGuid { get; set; }
        public string RecordValue { get; set; }
        public decimal? RecordWeight { get; set; }
        public decimal? RecordAmount { get; set; }
        public string RecordDisease { get; set; }
        public string RecordNext { get; set; }
    }
    public partial class UpdateWeightParams
    {
        public string Type { get; set; }
        public string RecordGuid { get; set; }
        public string RecordValue { get; set; }
        public decimal? RecordWeight { get; set; }
        public decimal? RecordAmount { get; set; }
        public string RecordDisease { get; set; }
        public string RecordNext { get; set; }
public string OrderNo { get; set; }
    }
}