// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PigFarm.DTO
{
    public partial class RecordInOut2PigDto
    {
        public decimal Id { get; set; }
        public string InOutGuid { get; set; }
        public string PigGuid { get; set; }
public string OrderNo { get; set; }
    }
}