// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PigFarm.Models
{
    public partial class RecordDiagnosis
    {
        public int Id { get; set; }
        public string FarmGuid { get; set; }
        public string Type { get; set; }
        public string MakeOrderGuid { get; set; }
        public string Comment { get; set; }
        public DateTime? CreateDate { get; set; }
        public decimal? CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public decimal? UpdateBy { get; set; }
        public DateTime? DeleteDate { get; set; }
        public decimal? DeleteBy { get; set; }
        public decimal? Status { get; set; }
        public string Guid { get; set; }
        public DateTime? EstDate { get; set; }
        public DateTime? ApplyDate { get; set; }
        public string ApplyReason { get; set; }
        public string ApplyGuid { get; set; }
        public DateTime? RejectDate { get; set; }
        public string RejectReason { get; set; }
        public string RejectGuid { get; set; }
        public DateTime? ExecuteDate { get; set; }
        public string ExecuteReason { get; set; }
        public string ExecuteGuid { get; set; }
        public string Diagnosis { get; set; }
        public DateTime? AgreeDate { get; set; }
        public string AgreeReason { get; set; }
        public string AgreeGuid { get; set; }
        public string UpperRecord { get; set; }
        public string UpperGuid { get; set; }
        public DateTime? InventoryDate { get; set; }
        public string InventoryReason { get; set; }
        public string InventoryGuid { get; set; }
        public DateTime? VeterinaryDate { get; set; }
        public string VeterinaryReason { get; set; }
        public string VeterinaryGuid { get; set; }
        public decimal? DiagnosisAmount { get; set; }
        public string DiagnosisDescribe { get; set; }
        public string DiagnosisNo { get; set; }
        public DateTime? DiagnosisDate { get; set; }
        public DateTime? DiagnosisWithdrawalDate { get; set; }
        public decimal? DiagnosisWithdrawalDays { get; set; }
        public string DiagnosisDoctor { get; set; }
        public string DiagnosisPhysician { get; set; }
        public string DiagnosisSymptom { get; set; }
        public string DiagnosisCheck { get; set; }
        public string DiagnosisTreatment { get; set; }
        public string DiagnosisMedicine { get; set; }
        public decimal? DiagnosisDose { get; set; }
        public string DiagnosisWay { get; set; }
        public DateTime? DiagnosisFirstDosDay { get; set; }
        public decimal? DiagnosisTimes { get; set; }
    }
}