// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PigFarm.Models
{
    public partial class RecordInOut2Pig
    {
        public decimal Id { get; set; }
        public string InOutGuid { get; set; }
        public string PigGuid { get; set; }
    }
}