// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PigFarm.Models
{
    public partial class PigDisease2pen
    {
        public decimal Id { get; set; }
        public string PigDiseaseMasterGuid { get; set; }
        public string PenGuid { get; set; }
    }
}