// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PigFarm.DTO
{
    public partial class PigFarmVectorControlDto
    {
        public decimal Id { get; set; }
        public string FarmGuid { get; set; }
        public string MakeOrderGuid { get; set; }
        public string PigType { get; set; }
        public string Type { get; set; }
        public string UpperGuid { get; set; }
        public DateTime? EstDate { get; set; }
        public string EstTime { get; set; }
        public DateTime? RecordDate { get; set; }
        public string RecordTime { get; set; }
        public string VectorControlGuid { get; set; }
        public string UseType { get; set; }
        public string UseUnit { get; set; }
        public string Capacity { get; set; }
        public string Frequency { get; set; }
        public string ApplyDays { get; set; }
        public string Comment { get; set; }
        public DateTime? CreateDate { get; set; }
        public decimal? CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public decimal? UpdateBy { get; set; }
        public DateTime? DeleteDate { get; set; }
        public decimal? DeleteBy { get; set; }
        public decimal? Status { get; set; }
        public string Guid { get; set; }
        public string PigGuid { get; set; }
        public string PenGuid { get; set; }
        public string RoomGuid { get; set; }
        public string TypeName { get; set; }
        public string UseTypeName { get; set; }
        public string UseUnitName { get; set; }
        public string CapacityName { get; set; }
        public string FrequencyName { get; set; }
        public string ApplyDaysName { get; set; }
        public string VectorControlName { get; set; }


    }
}