export interface Pig {
  id: number;
  pigType: string;
  phase: string;
  outsourcing: number | null;
  farmGuid: string;
  areaGuid: string;
  barnGuid: string;
  roomGuid: string;
  penGuid: string;
  cullingTankGuid: string;
  fatherGuid: string;
  motherGuid: string;
  idno: string;
  earNo: string;
  earTag: string;
  rfidtag: string;
  birthday: any;
  dayAge: number | null;
  sex: number | null;
  weight: number | null;
  weightDate: string | null;
  weightDayAge: number | null;
  breed: number | null;
  birthPenGuid: number | null;
  enterOrigin: number | null;
  enterDate: string | null;
  enterDept: number | null;
  transferMoney: number | null;
  transferDate: string | null;
  transferFrom: number | null;
  farrowStatus: number | null;
  farrowComment: string;
  suckingCheckInDate: string | null;
  suckingCheckInStatus: number | null;
  suckingCheckOutDate: string | null;
  suckingCheckOutStatus: number | null;
  growerCheckInDate: string | null;
  growerCheckInStatus: number | null;
  growerCheckOutDate: string | null;
  growerCheckOutStatus: number | null;
  finisherCheckInDate: string | null;
  finisherCheckInStatus: number | null;
  finisherCheckOutDate: string | null;
  finisherCheckOutStatus: number | null;
  nurseryCheckInDate: string | null;
  nurseryCheckInStatus: number | null;
  nurseryCheckOutDate: string | null;
  nurseryCheckOutStatus: number | null;
  comment: string;
  cancelFlag: string;
  createDate: string | null;
  createBy: number | null;
  updateDate: string | null;
  updateBy: number | null;
  status: number | null;
  guid: string;
  makeOrderGuid: string;
  sequence: number | null;
  phaseName: string;

}
